(defun python-template()
  (interactive)
  (insert "##############################\n#\n#")
  (insert (getenv "USER"))
  (insert "#\n")
  (insert "#")
  (insert (format-time-string "%Y-%m-%d"))
  (insert "\n")
  (insert "#################################")
  (insert "\n")
  (insert "\n")
  (insert "\n")
  (insert "#start code here")
  (insert "\n")
  (insert "\n")
  (insert "\n")
  (insert "def function_1(arg):")
  (insert "\n")
  (insert "    \"\"\"")
  (insert "\n")
  (insert "    \"\"\"")
  (insert "\n")
  (insert "    #some code")
  (insert "\n")
  (insert "\n")
  (insert "\n")
  (insert "\n")
  (insert "\n")
  (insert "def main():")
  (insert "\n")
  (insert "    \"\"\"")
  (insert "    Main block of code for workflow")
  (insert "\n")
  (insert "    \"\"\"")
  (insert "\n")
  (insert "    #some code")
  (insert "\n")
  (insert "\n")
  (insert "\n")
  (insert "\n")
  (insert "\n")
  (insert "if __name__==\"__main__\":")
  (insert "\n")
  (insert "    main()")
)

(defun python-docstring()
  (interactive)
  (insert  "    \"\"\"\n")
  (insert  "    DESCRIPTION:\n")
  (insert  "    INPUTS  :\n")
  (insert  "          in1 - \n\n")
  (insert  "          in2 - \n\n")
  (insert  "          in3 - \n\n")
  (insert  "    OUTPUTS :\n")
  (insert  "          out1 - \n\n")
  (insert  "          out2 - \n\n")
  (insert  "          out3 - \n\n")
  (insert  "    DEPENDENCEIES : \n\n")
  (insert  "    \"\"\"\n")
)
